name: login
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.6 <4.0.0'

# Add regular dependencies here.
dependencies:
  models:
    path: ../../models
  common_dependencies:
    path: ../../common_dependencies 
  common_ui:
    path: ../../common_ui 


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
